version: '3.8'    
services:      
    web-server:        
        container_name: web-server   
        restart: always  
        build:          
            context: ./src/php          
            dockerfile: ../../WebServer_Dockerfile        
        depends_on:         
        - mysql-server       
        volumes:        
        - ./src/php:/var/www/html/        
        ports:         
        - "8000:80"    
    mysql-server:      
        container_name: mysql-server      
        image: mysql      
        restart: always      
        environment:        
            MYSQL_ROOT_PASSWORD: SNH_ROOT_PASSWORD        
            MYSQL_DATABASE: secure_book_selling_db        
            MYSQL_USER: SNH       
            MYSQL_PASSWORD: SNH_USER_PASSWORD    
        ports:      
        - "9906:3306"
    phpmyadmin:         
        image: phpmyadmin/phpmyadmin    
        ports:      
        - "8080:80"    
        restart: always    
        environment:      
            PMA_HOST: mysql-server    
        depends_on:      
        - mysql-server