version: '3.8'
services:
    web-server:
        container_name: web-server
        image: php:8.2-apache
        restart: always
        depends_on:
            - mysql-server
        env_file:
            - .env
        volumes:
            # base directory of the website
            - ./src:/var/www/html/
            # storage of the e-books
            - ./apache_conf/e-books:/home/bookselling/e-books-mounted
            # https config files
            - ./apache_conf/ssl_conf/certificates/bookselling:/etc/ssl/ssl_certificates
            - ./apache_conf/ssl_conf/sites-available:/etc/apache2/sites-available
            # web server configuration files
            - ./apache_conf/config_system.sh:/home/bookselling/config_system.sh
        command: /bin/bash -c "/home/bookselling/config_system.sh"
        ports:         
        - "127.0.0.1:443:443"
        networks:
            network:
                ipv4_address: 10.5.0.2
    mysql-server:
        container_name: mysql-server
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "127.0.0.1:9906:3306"
        volumes:
            - ./mysql_conf/my/custom:/etc/mysql/conf.d
            - ./mysql_conf/secure_book_selling_db.sql:/docker-entrypoint-initdb.d/secure_book_selling_db.sql
        networks:
            network:
                ipv4_address: 10.5.0.5
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "127.0.0.1:8800:80"
        restart: always
        environment:
            PMA_HOST: mysql-server
        depends_on:
            - mysql-server
        networks:
            network:
                ipv4_address: 10.5.0.4

networks:
    network:
        driver: bridge
        ipam:
            config:
                -
                    subnet: 10.5.0.0/16
                    gateway: 10.5.0.1