version: '3.8'    
services:      
    web-server:        
        container_name: web-server   
        restart: always  
        build:          
            context: .         
            dockerfile: WebServer_Dockerfile        
        depends_on:         
        - mysql-server       
        volumes:        
        - ./src:/var/www/html/        
        ports:         
        - "8000:80"  
        networks:
            network:
                ipv4_address: 10.5.0.2  
    mysql-server:      
        container_name: mysql-server      
        image: mysql      
        restart: always      
        environment:        
            MYSQL_ROOT_PASSWORD: password        
            MYSQL_DATABASE: secure_book_selling_db        
            MYSQL_USER: SNH       
            MYSQL_PASSWORD: password   
        ports:      
        - "9906:3306"
        volumes:        
        # - ./mysql_server/mysql_volume:/var/lib/mysql/
        - ./mysql_server/my/custom:/etc/mysql/conf.d
        networks:
            network:
                ipv4_address: 10.5.0.5
    phpmyadmin:         
        image: phpmyadmin/phpmyadmin    
        ports:      
        - "8080:80"    
        restart: always    
        environment:      
            PMA_HOST: mysql-server    
        depends_on:      
        - mysql-server
        networks:
            network:
                ipv4_address: 10.5.0.4

networks:
    network:
        driver: bridge
        ipam:
            config:
                -
                    subnet: 10.5.0.0/16
                    gateway: 10.5.0.1